[package]
name = "railway_layout_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = "2.0"
once_cell = "1.8.0"